### ISSUE TITLE
Tarefa 2 - Bug Fix

### ISSUE THREAD

**Issue by matheussilvasousa** [TPII20152/SB08#1]
O método debitar(double valor) da classe ContaImposto não está observando o caso excepcional de saldo insuficiente. Corrija esse bug!

**Comment by JonasMartins** [comment]
Como minha primeira contribuição, fiz a solução desse bug coisa bem simples apenas para começar o trabalho.

**Comment by lincolnrocha** [comment]
@JonasMartins se você corrigiu esse Bug, por que não vejo o commit associado? Pelo visto, a issue continua aberta? Feche a issue utilizando uma mensagem de commit que informe que o bug foi corrigido! Ou associe o commit que corrigiu o bug à time-line da issue ao fechar a issue.

**Comment by JonasMartins** [comment]
@lincolnrocha Eu deixei a issue aberta pensando em uma eventual alteração de outro membro, mas pela simplicidade da tarefa realmente é melhor fecha-la, e ajudar nas outras tarefas. Eu apenas fiz minha alteração e mandei pro master, não soube commitar aqui na issue, e fecha-la com o commite, que está em code<>, vou dar uma pesquisada na próxima faço corretamente.

**Comment by JonasMartins** [comment]
@lincolnrocha Eu deixei a issue aberta pensando em uma eventual alteração de outro membro, mas pela simplicidade da tarefa realmente é melhor fecha-la, e ajudar nas outras tarefas. Eu apenas fiz minha alteração e mandei pro master, não soube commitar aqui na issue, e fecha-la com o commite, que está em code<>, vou dar uma pesquisada na próxima faço corretamente.
