### ISSUE TITLE
Tarefa 3 - Bug Fix

### ISSUE THREAD

**Issue by matheussilvasousa** [TPII20152/SB08#2]
A classe ArrayContas possui limite fixo de 100 posições para armazenar contas. Ela deve suportar tamanho ilimitado. Corrija esse bug!

**Comment by ArthurBrito** [comment]
@lincolnrocha Professor, tentei aqui por umas 3 horas tentar usar ArrayList pra não ter problema com tamanho máximo. Mas não consegui fazer rodar sem bug. Continuo tentando no ArrayList ou faço outra solução usando Array mesmo?

**Comment by lincolnrocha** [comment]
@ArthurBrito a solução deve ser sua (da sua equipe)! Quem disse que era pra usar ArrayList? Corrija o Bug, essa é a tarefa!
