### ISSUE TITLE
Tarefa 5 - New Feature

### ISSUE THREAD

**Issue by matheussilvasousa** [TPII20152/SB08#4]
Implementar uma GUI com Java Swing para o Sistema Bancário (Terminal de Autoatendimento).

**Comment by ArthurBrito** [comment]
@matheussilvasousa vamos quebrar essa ISSUE em menores?

**Comment by matheussilvasousa** [comment]
Tudo bem @ArthurBrito, afinal são várias interfaces que podem ser feitas baseado no sistema. Mas, segundo o professor, essa é uma issue que não é bem uma prioridade e que poderíamos deixar pra depois. Fica a seu critério!
