### ISSUE TITLE
Tarefa 7.1 - Casos de Teste (VectorContas, ArrayContas)

### ISSUE THREAD

**Issue by matheussilvasousa** [TPII20152/SB08#6]
Com base nos Casos de Teste e Cenários de Testes descritos acima, especifique e implemente novos Casos de Teste e Cenários de Teste para as classes: VectorContas, ArrayContas. Para lidar com testes onde exceções são esperadas use a anotação @Test (expected = <NomeDaExceção>.class).

**Comment by thiagonrodrigues30** [comment]
Issue modificada para os casos de uso atenderem somente as classes VectorContas e ArrayContas devido a falta de implementação de alguns elementos na classe BancoBrasil no momento.
